# Generated by Django 4.1.1 on 2022-09-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_details_kcno'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment_details_1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_id', models.IntegerField()),
                ('file', models.CharField(max_length=250)),
                ('analysis_score', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='assignment_details_2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_id', models.IntegerField()),
                ('file', models.CharField(max_length=250)),
                ('links', models.CharField(max_length=250)),
                ('analysis_score', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='assignment_details_3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_id', models.IntegerField()),
                ('content', models.CharField(max_length=1000)),
                ('links_content', models.CharField(max_length=1000)),
                ('analysis_score', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='designation_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='staff_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('desg_id', models.IntegerField()),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=1000)),
                ('pin', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='staff_messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.IntegerField()),
                ('sub', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=350)),
                ('dt', models.CharField(max_length=20)),
                ('tm', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='staff_student_map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='student_assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('title', models.CharField(max_length=10)),
                ('remarks', models.CharField(max_length=10)),
                ('dt', models.CharField(max_length=10)),
                ('tm', models.CharField(max_length=10)),
                ('type_id', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('rollno', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('addr', models.CharField(max_length=1000)),
                ('pin', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='user_details',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
