# Generated by Django 4.0 on 2024-04-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_assignment_details_1_assignment_details_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
    ]
